name: Application Size

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the application's source code
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com
          scope: "@university-of-york"
          always-auth: true

      - name: Check the application's file size
        uses: preactjs/compressed-size-action@e2bfc4b346d78f9a3c7e8a2e22bcbd285a25fafa
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          build-script: package
          pattern: .serverless/*.zip
          compression: none
          minimum-change-threshold: 1024
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          AWS_ACCOUNT_ID: ${{ secrets.DEV_AWS_ACCOUNT_ID }}

