name: Run XO and Prettier
on:
  pull_request:
  workflow_dispatch:

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the application's source code
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com
          scope: "@university-of-york"
          always-auth: true

      - name: Install application dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Check code is formatted correctly
        run: npm run checkformat

      - name: Check code conforms to linting rules
        run: npm run lint

      - name: Check tests run
        run: npm run test
